# Generated by Django 5.0 on 2023-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='movements',
            field=models.ManyToManyField(to='app1.movement'),
        ),
    ]
