# Generated by Django 5.0 on 2023-12-06 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_bank_account_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
