# Generated by Django 5.0 on 2023-12-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_transfer_owner_transfer_transmitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='message',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transfer',
            name='title',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='movements',
            field=models.ManyToManyField(blank=True, to='app1.movement'),
        ),
    ]
